[package]
name = "mikeos"
version = "0.0.1"
authors = ["Mike Roll <scaryspiderpig@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
rlibc = "1.0.0"
spin = "0.4.2"
